# Generated by Django 5.2 on 2025-04-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scoring_notes',
            field=models.TextField(blank=True, help_text='Notes related to project scoring or evaluation', null=True),
        ),
        migrations.AlterModelTable(
            name='project',
            table='project_requests',
        ),
    ]
