# Generated by Django 5.2 on 2025-04-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_scoring_notes_alter_project_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='notes',
            new_name='triage_notes',
        ),
        migrations.AddField(
            model_name='project',
            name='final_priority',
            field=models.IntegerField(blank=True, help_text='Final priority score as a number', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final score as a decimal number', max_digits=5, null=True),
        ),
    ]
