# Generated by Django 5.2 on 2025-04-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_notes_project_triage_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('new_submission', 'New Submission'), ('process_improvement', 'Process Improvement'), ('it_governance', 'IT Governance'), ('erp_governance', 'ERP Governance'), ('data_governance', 'Data Governance')], default='new_submission', help_text='Type of project submission', max_length=20),
        ),
    ]
