# Generated by Django 5.2 on 2025-04-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='final_priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], help_text='Final priority score (1=Low, 2=Medium, 3=High)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='final_score',
            field=models.IntegerField(blank=True, help_text='Final score (0-100)', null=True),
        ),
    ]
