# Generated by Django 5.2 on 2025-04-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_final_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='strategic_alignment',
            field=models.IntegerField(blank=True, help_text='Strategic alignment score (0-100)', null=True),
        ),
    ]
