# Generated by Django 5.2 on 2025-04-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_cost_benefit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_impact',
            field=models.IntegerField(blank=True, help_text='User impact and adoption score (1-5)', null=True),
        ),
    ]
