# Generated by Django 5.2 on 2025-04-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_user_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ease_of_implementation',
            field=models.IntegerField(blank=True, help_text='Ease of implementation score (1-5)', null=True),
        ),
    ]
