# Generated by Django 5.2 on 2025-04-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_vendor_reputation_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='security_compliance',
            field=models.IntegerField(blank=True, help_text='Security and compliance score (1-5)', null=True),
        ),
    ]
