# Generated by Django 5.2 on 2025-04-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_security_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='student_centered',
            field=models.IntegerField(blank=True, help_text='Student-centered score (1-5)', null=True),
        ),
    ]
