# Generated by Django 5.2 on 2025-04-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_student_centered'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='college_centered',
            field=models.IntegerField(blank=True, help_text='College-centered score (1-5)', null=True),
        ),
    ]
