# Generated by Django 5.2 on 2025-04-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_final_priority_projectscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscore',
            name='final_score',
            field=models.FloatField(blank=True, help_text='Calculated final score for this user', null=True),
        ),
    ]
