# Generated by Django 5.2 on 2025-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projectscore_final_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='final_score',
            field=models.FloatField(blank=True, help_text='Final score', null=True),
        ),
    ]
