# Generated by Django 5.2 on 2025-04-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_project_final_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='college_centered',
        ),
        migrations.RemoveField(
            model_name='projectscore',
            name='college_centered',
        ),
    ]
