# Generated by Django 5.2 on 2025-04-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_triagechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectscore',
            name='cost_benefit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='ease_of_implementation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='security_compliance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='strategic_alignment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='student_centered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='user_impact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='vendor_reputation_support',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TriageChange',
        ),
    ]
