# Generated by Django 5.2 on 2025-05-13 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_remove_triage_change_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectscore',
            name='cost_benefit',
            field=models.IntegerField(blank=True, help_text='Cost benefit score (1-5)', null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='ease_of_implementation',
            field=models.IntegerField(blank=True, help_text='Ease of implementation score (1-5)', null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='final_score',
            field=models.FloatField(blank=True, help_text='Calculated final score for this user', null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='security_compliance',
            field=models.IntegerField(blank=True, help_text='Security and compliance score (1-5)', null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='strategic_alignment',
            field=models.IntegerField(blank=True, help_text='Strategic alignment score (1-5)', null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='student_centered',
            field=models.IntegerField(blank=True, help_text='Student-centered score (1-5)', null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='user_impact',
            field=models.IntegerField(blank=True, help_text='User impact and adoption score (1-5)', null=True),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='vendor_reputation_support',
            field=models.IntegerField(blank=True, help_text='Vendor reputation and support score (1-5)', null=True),
        ),
        migrations.CreateModel(
            name='TriageNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_note_history', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
