# Generated by Django 5.2.2 on 2025-06-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_project_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('Pending_Review', 'Pending Review'), ('Under_Review_Triage', 'Under Review - Triage'), ('Under_Review_Scoring', 'Under Review - Scoring'), ('Under_Review_Final_Scoring', 'Under Review - Final Scoring')], default='Pending_Review', help_text='Current stage of the project', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('archived', 'Archived'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True),
        ),
    ]
