# Generated by Django 5.2 on 2025-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('not_yet_decided', 'Not Yet Decided'), ('process_improvement', 'Process Improvement'), ('it_governance', 'IT Governance'), ('erp_governance', 'ERP Governance'), ('data_governance', 'Data Governance')], default='not_yet_decided', help_text='Type of request submission', max_length=20, verbose_name='Request Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review_triage', 'Under Review - Triage'), ('under_review_scoring', 'Under Review - Scoring'), ('under_review_final_scoring', 'Under Review - Final Scoring'), ('completed', 'Completed'), ('archived', 'Archived'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
