# Generated by Django 5.2 on 2025-09-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_project_project_type_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('Pending_Review', 'Pending Review'), ('Under_Review_Triage', 'Under Review - Triage'), ('Under_Review_Scoring', 'Under Review - Scoring'), ('Under_Review_Final_Scoring', 'Under Review - Final Scoring'), ('Governance_Closure', 'Governance Closure')], default='Pending_Review', help_text='Current stage of the project', max_length=30),
        ),
    ]
