# Generated by Django 5.2 on 2025-09-12 14:35

from django.db import migrations


def update_stage_values(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    
    # Update Under_Review_Scoring to Under_Review_governance
    Project.objects.filter(stage='Under_Review_Scoring').update(stage='Under_Review_governance')
    
    # Update Under_Review_Final_Scoring to Under_Review_Final_governance
    Project.objects.filter(stage='Under_Review_Final_Scoring').update(stage='Under_Review_Final_governance')


def reverse_stage_values(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    
    # Reverse the changes
    Project.objects.filter(stage='Under_Review_governance').update(stage='Under_Review_Scoring')
    Project.objects.filter(stage='Under_Review_Final_governance').update(stage='Under_Review_Final_Scoring')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_add_governance_closure_stage'),
    ]

    operations = [
        migrations.RunPython(update_stage_values, reverse_stage_values),
    ]
