# Generated by Django 5.2 on 2025-09-12 14:56

from django.db import migrations


def update_status_values(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    
    # Update under_review_scoring to under_review_governance
    Project.objects.filter(status='under_review_scoring').update(status='under_review_governance')
    
    # Update under_review_final_scoring to under_review_final_governance
    Project.objects.filter(status='under_review_final_scoring').update(status='under_review_final_governance')


def reverse_status_values(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    
    # Reverse the changes
    Project.objects.filter(status='under_review_governance').update(status='under_review_scoring')
    Project.objects.filter(status='under_review_final_governance').update(status='under_review_final_scoring')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_update_stage_values'),
    ]

    operations = [
        migrations.RunPython(update_status_values, reverse_status_values),
    ]
