# Generated by Django 5.2 on 2025-09-16 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_update_status_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('not_yet_decided', 'Not Yet Decided'), ('process_improvement', 'Process Improvement'), ('it_governance', 'IT Governance'), ('erp_governance', 'ERP Governance'), ('ai_governance', 'AI Governance')], default='not_yet_decided', help_text='Type of request submission', max_length=20, verbose_name='Request Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('Pending_Review', 'Pending Review'), ('Under_Review_Triage', 'Under Review - Triage'), ('Under_Review_governance', 'Under Review - Governance'), ('Under_Review_Final_governance', 'Under Review - Final Governance'), ('Governance_Closure', 'Governance Closed')], default='Pending_Review', help_text='Current stage of the project', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review_triage', 'Under Review - Triage'), ('under_review_governance', 'Under Review - Governance'), ('under_review_final_governance', 'Under Review - Final Governance'), ('completed', 'Completed'), ('archived', 'Archived'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='TriageChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Name of the field that was changed', max_length=50)),
                ('field_label', models.CharField(help_text='Human-readable label for the field', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_change_history', to='projects.project')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
