# Generated by Django 5.2 on 2025-10-16 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_add_triage_change_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('Pending_Review', 'Pending Review'), ('Under_Review_Triage', 'Under Review - Triage'), ('Under_Review_governance', 'Under Review - Governance'), ('Under_Review_Final_governance', 'Under Review - Final Governance'), ('Governance_Closure', 'Governance Closed'), ('Deleted', 'Deleted')], default='Pending_Review', help_text='Current stage of the project', max_length=30),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes vs external communications')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='projects.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
