# Generated by Django 5.2 on 2025-10-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_alter_project_stage_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sdp_link',
            field=models.URLField(blank=True, help_text='SDP Link URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sdp_ticket_number',
            field=models.CharField(blank=True, help_text='SDP Ticket Number', max_length=50, null=True),
        ),
    ]
