# Generated by Django 5.2.8 on 2025-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_project_sdp_link_project_sdp_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('Pending_Review', 'Pending Review'), ('Under_Review_Triage', 'Under Review - Triage'), ('Under_Review_governance', 'Under Review - Governance'), ('Under_Review_Final_governance', 'Under Review - Final Governance'), ('Governance_Closure', 'Governance Closed - Recommended'), ('Governance_Closure_Not_Recommended', 'Governance Closed - Not Recommended'), ('Deleted', 'Deleted')], default='Pending_Review', help_text='Current stage of the project', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Recommended'), ('rejected', 'Not Recommended'), ('under_review_triage', 'Under Review - Triage'), ('under_review_governance', 'Under Review - Governance'), ('under_review_final_governance', 'Under Review - Final Governance'), ('completed', 'Completed'), ('archived', 'Archived'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
