# Generated by Django 5.2.8 on 2025-11-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_rename_contact_person_to_technician'),
        ('projects', '0038_add_triage_assignment_fields'),
    ]

    operations = [
    ]
