"""
Django settings for project_intake project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")  # loads your local .env

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-&*hb2%)zdi-5-w&u0pl7*q5)g^z!7sad6(kry_rj#nkzgj9m^$'
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-please-change")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("1", "true", "yes")

# Force DEBUG to False for production safety
# if not DEBUG:
#     DEBUG = False

# ALLOWED_HOSTS = ['localhost', '127.0.0.1']
# Add both Azure default domain and custom domain
DEFAULT_HOSTS = "localhost,127.0.0.1,govapp-fbhde3c8ffg9fbf9.westus2-01.azurewebsites.net,governance.coloradocollege.app"
ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", DEFAULT_HOSTS).split(",")]

# Helpful for Azure (avoids CSRF issues on the cloud hostname)
CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS if h not in ("localhost", "127.0.0.1")]

# Behind Azure's proxy, this helps Django detect HTTPS correctly
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'projects',
    'cas',
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",  # add right after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'cas.middleware.ProxyMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'cas.middleware.CASMiddleware',
]

PROXY_DOMAIN = 'governance.coloradocollege.app'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'cas.backends.CASBackend',
)

CAS_SERVER_URL = "https://cas.coloradocollege.edu/cas/"  # Replace with your institution's CAS URL
CAS_LOGOUT_COMPLETELY = True
CAS_PROVIDE_URL_TO_LOGOUT = True
# Force CAS to use custom domain instead of Azure default domain
CAS_SERVICE_URL = "https://governance.coloradocollege.app"
CAS_ROOT_PROXIED_AS = "https://governance.coloradocollege.app"
CAS_REDIRECT_URL = "https://governance.coloradocollege.app/"

# CAS User Attribute Mapping - captures email and other info from CAS response
# Based on Colorado College CAS admin specifications
# Mapping to Django User model fields only
CAS_RENAME_ATTRIBUTES = {
    'mail': 'email',           # Email address
    'givenName': 'first_name', # First Name  
    'sn': 'last_name',        # Last Name
}

# Auto-create user accounts with attributes from CAS
CAS_CREATE_USER = True
CAS_UPDATE_USER_ATTRIBUTES = True

ROOT_URLCONF = 'project_intake.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_intake.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'governance_db'),
        'USER': os.getenv('POSTGRES_USER', 'csmart'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': os.getenv('POSTGRES_HOST', 'az-westus2-eis-postgres1.postgres.database.azure.com'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "projects/static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Use WhiteNoise's compressed manifest storage for cache-busting
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SITE_ID = 1

# Allauth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True

# Helpful for Azure (avoids CSRF issues on the cloud hostname)
CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS if h not in ("localhost", "127.0.0.1")]

# Behind Azure’s proxy, this helps Django detect HTTPS correctly
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'cas',
    # 'cas',
    'projects',
    'crispy_forms',
    'crispy_bootstrap5',
    'cas',  # Emergency disable - ModuleNotFoundError: No module named 'cas'
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.sites',
    'allauth',  # Emergency disable - django-allauth removed from requirements.txt
    'allauth.account',  # Emergency disable - django-allauth removed from requirements.txt
    'allauth.socialaccount',  # Emergency disable - django-allauth removed from requirements.txt
]

if ENABLE_AZURE_AD:
    INSTALLED_APPS.append('allauth.socialaccount.providers.microsoft')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",  # add right after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

if ENABLE_CAS:
    INSTALLED_APPS.append('cas')
    MIDDLEWARE.insert(3, 'cas.middleware.ProxyMiddleware')
    MIDDLEWARE.append('cas.middleware.CASMiddleware')
]

if ENABLE_CAS:
    INSTALLED_APPS.append('cas')
    MIDDLEWARE.insert(3, 'cas.middleware.ProxyMiddleware')
    MIDDLEWARE.append('cas.middleware.CASMiddleware')

PROXY_DOMAIN = 'governance.coloradocollege.app'
PROXY_DOMAIN = 'governance.coloradocollege.app'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
<<<<<<< HEAD
    'allauth.account.auth_backends.AuthenticationBackend',
    'cas.backends.CASBackend',  # Enable this when CAS is ready
=======
    # 'allauth.account.auth_backends.AuthenticationBackend',  # Emergency disable - django-allauth removed from requirements.txt
    # 'cas.backends.CASBackend',  # Emergency disable - app crash
>>>>>>> 893da6e (Emergency fix: Comment out CAS and allauth components causing deployment failures)
)

if ENABLE_CAS:
    AUTHENTICATION_BACKENDS += ('cas.backends.CASBackend',)

if ENABLE_CAS:
    CAS_SERVER_URL = "https://cas.coloradocollege.edu/cas/"  # Replace with your institution's CAS URL
    CAS_LOGOUT_COMPLETELY = True
    CAS_PROVIDE_URL_TO_LOGOUT = True
    # Force CAS to use custom domain instead of Azure default domain
    CAS_SERVICE_URL = "https://governance.coloradocollege.app"
    CAS_ROOT_PROXIED_AS = "https://governance.coloradocollege.app"
    CAS_REDIRECT_URL = "https://governance.coloradocollege.app/"

    # CAS User Attribute Mapping - captures email and other info from CAS response
    # Based on Colorado College CAS admin specifications
    # Mapping to Django User model fields only
    CAS_RENAME_ATTRIBUTES = {
        'mail': 'email',           # Email address
        'givenName': 'first_name', # First Name  
        'sn': 'last_name',        # Last Name
    }

    # Auto-create user accounts with attributes from CAS
    CAS_CREATE_USER = True
    CAS_UPDATE_USER_ATTRIBUTES = True

ROOT_URLCONF = 'project_intake.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_intake.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': os.getenv('POSTGRES_DB', 'governance_db'),
#        'USER': os.getenv('POSTGRES_USER', 'csmart'),
#        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
#        'HOST': os.getenv('POSTGRES_HOST', 'az-westus2-eis-postgres1.postgres.database.azure.com'),
#        'PORT': os.getenv('POSTGRES_PORT', '5432'),
#    }
#}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': os.getenv('POSTGRES_DB', 'governance_db'),
#        'USER': os.getenv('POSTGRES_USER', 'csmart'),
#        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
#        'HOST': os.getenv('POSTGRES_HOST', 'az-westus2-eis-postgres1.postgres.database.azure.com'),
#        'PORT': os.getenv('POSTGRES_PORT', '5432'),
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "projects/static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Use WhiteNoise’s compressed manifest storage for cache-busting
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SITE_ID = 1

# Allauth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True

SOCIALACCOUNT_STORE_TOKENS = True

SOCIALACCOUNT_PROVIDERS = {}

if ENABLE_AZURE_AD:
    AZURE_AD_TENANT_ID = os.getenv("DJANGO_AZURE_TENANT_ID", "common")
    AZURE_AD_CLIENT_ID = os.getenv("DJANGO_AZURE_CLIENT_ID", "")
    AZURE_AD_CLIENT_SECRET = os.getenv("DJANGO_AZURE_CLIENT_SECRET", "")
    AZURE_AD_GROUP_MAPPING_RAW = os.getenv("DJANGO_AZURE_GROUP_MAPPING", "")

    AZURE_AD_SCOPES = [
        'openid',
        'email',
        'profile',
        'offline_access',
        'User.Read',
        'GroupMember.Read.All',
    ]

    AZURE_AD_GROUP_MAPPING = {}
    if AZURE_AD_GROUP_MAPPING_RAW:
        for item in AZURE_AD_GROUP_MAPPING_RAW.split(','):
            key, _, value = item.partition(':')
            if key and value:
                AZURE_AD_GROUP_MAPPING[key.strip()] = value.strip()

    SOCIALACCOUNT_PROVIDERS['microsoft'] = {
        'TENANT': AZURE_AD_TENANT_ID,
        'SCOPE': AZURE_AD_SCOPES,
        'AUTH_PARAMS': {'prompt': 'select_account'},
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': True,
        'APP': {
            'client_id': AZURE_AD_CLIENT_ID,
            'secret': AZURE_AD_CLIENT_SECRET,
        },
    }

SOCIALACCOUNT_STORE_TOKENS = True

SOCIALACCOUNT_PROVIDERS = {}

if ENABLE_AZURE_AD:
    AZURE_AD_TENANT_ID = os.getenv("DJANGO_AZURE_TENANT_ID", "common")
    AZURE_AD_CLIENT_ID = os.getenv("DJANGO_AZURE_CLIENT_ID", "")
    AZURE_AD_CLIENT_SECRET = os.getenv("DJANGO_AZURE_CLIENT_SECRET", "")
    AZURE_AD_GROUP_MAPPING_RAW = os.getenv("DJANGO_AZURE_GROUP_MAPPING", "")

    AZURE_AD_SCOPES = [
        'openid',
        'email',
        'profile',
        'offline_access',
        'User.Read',
        'GroupMember.Read.All',
    ]

    AZURE_AD_GROUP_MAPPING = {}
    if AZURE_AD_GROUP_MAPPING_RAW:
        for item in AZURE_AD_GROUP_MAPPING_RAW.split(','):
            key, _, value = item.partition(':')
            if key and value:
                AZURE_AD_GROUP_MAPPING[key.strip()] = value.strip()

    SOCIALACCOUNT_PROVIDERS['microsoft'] = {
        'TENANT': AZURE_AD_TENANT_ID,
        'SCOPE': AZURE_AD_SCOPES,
        'AUTH_PARAMS': {'prompt': 'select_account'},
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': True,
        'APP': {
            'client_id': AZURE_AD_CLIENT_ID,
            'secret': AZURE_AD_CLIENT_SECRET,
        },
    }
